spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.google.com
          predicates:
            - Query= url,google
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query= url,qq

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path= /api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
#http://localhost:88/api/product/category/listTree rewrite to  http://localhost:10000/product/category/listTree
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path= /** #all request with api as prefix will be routed to renren-fast
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
#http://localhost:88/api/captcha.jpg rewrite to  http://localhost:8080/renren-fast

